### ISSUE TITLE
Add support for strings in arguments, return values, and record fields

### ISSUE THREAD

**Issue by rfk** [rfk/uniffi-rs#3]
The example code so far only really exercises support for numbers. In practice we have a lot of code that uses strings, so we need to be able to deal with those conveniently and safely.

Adding support for strings would be a good opportunity for someone new to this codebase to get involved. They would need to:

* Think up a new [example](https://github.com/rfk/uniffi-rs/tree/master/examples) for some small code that uses strings, and try writing the IDL and the corresponding rust code for such a component. (It won't work yet, but having a specific example to get working is a good place to start).
  * Try to `cargo build` your example component, and confirm that it doesn't compile. If it *does* compile despite not having support for strings, that's a separate bug...
* Decide on how Strings should be passed across the FFI layer, both as individual arguments and when part of a compount record. Implement the rust half of that via the traits in [`uniffi::support`](https://github.com/rfk/uniffi-rs/blob/master/src/support/mod.rs).
  * My suggestion (which isn't necessarily the best way!) would be to
    * Implement `Lowerable` by writing out a fixed-size length field, followed by the body of the string.
    * Implement `Liftable` by doing the reverse, reading the fixed-size length followed by the string data.
    * Implement `ViaFfi` using the [`ffi_support::FfiStr`](https://docs.rs/ffi-support/0.4.0/ffi_support/struct.FfiStr.html) helper, which is what we use for strings in our hand-written rust component today.
* Add support for string types in [`uniffi:scaffolding`]. There's some placeholder stuff in there using `&str` and `FfiStr<>` but it'll probably need adjusting.
  * Try to get to a point where you can `cargo build` your example component and have it work successfully.
* Add support for strings in the [kotlin](https://github.com/rfk/uniffi-rs/blob/master/src/bindings/kotlin/gen_kotlin.rs) and [python](https://github.com/rfk/uniffi-rs/blob/master/src/bindings/python/gen_python.rs) bindings generators. The details here will depend on how strings are represented when crossing the FFI.
    * If you used `FfiStr` above, you might find that passing strings are arguments just works, because the native-code-binding layers of each language know how to pass a string object as a `const char*` in their FFI layers.
    * You'll need to add support for lifting and lowering strings as part of compound records; copy the approach taken for other primitive data types in these files.
    * Receiving strings as a return value and making sure they show up as native language string objects, is left as an exercise to the reader.

**Comment by rfk** [comment]
Just adding context/visbility here, @tarikeshaq mentioned that he's taking a look at this as he needs it for an experiment he's working on. @jhugman I recall you saying you might take a look as well, did you have anything you wanted to share to avoid repeat or conflicting work?

**Comment by jhugman** [comment]
I haven't the bandwidth to do this immediately. If you need it, please go
right ahead and steal.
